language: objective-c
osx_image: xcode7.3
xcode_workspace: push-sdk.xcworkspace
xcode_scheme: push-sdk
xcode_sdk: iphonesimulator

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master
    - 1.x_dev
